server:
  port: 8081

spring:
  application:
    name: report-workshop-service
  r2dbc:
    url: r2dbc:postgresql://neondb_owner:GQaLu2oDSTR6@ep-aged-lake-a4wjkmtd-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
    #url: ${DATABASE_URL}
    show-sql: true
    pool:
      max-size: 20
      validation-query: SELECT 1
      initial-size: 5
  codec:
    max-in-memory-size: 30MB

# Configuraci?n de Swagger/SpringDoc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    io.r2dbc: DEBUG
    org.springdoc: DEBUG

